const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const S={get:(k,d)=>{try{return JSON.parse(localStorage.getItem('kos16_'+k))??d}catch{return d}},set:(k,v)=>localStorage.setItem('kos16_'+k,JSON.stringify(v))};
const dayNames=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];const cats=['work','ministry','studies','health','family','finance','rest'];
const modes={normal:{label:'Normal',hint:'Balanced plan: ministry, studies, finance, health, family.',focus:['Top 3','free time','steady progress']},vacation:{label:'Vacation',hint:'Protect rest. Only essentials and family rhythms stay active.',focus:['Rest','family','minimum commitments']},'heavy-ministry':{label:'Heavy Ministry',hint:'Ministry gets first open deep-work blocks. Coursera stays away from Bible Study windows.',focus:['Bible Study','people reminders','prayer']},'financial-push':{label:'Financial Push',hint:'Finance/Uber gets priority, but only if the free slot is at least 2 hours.',focus:['Uber blocks','debt payoff','expense discipline']},recovery:{label:'Recovery',hint:'Sleep, prayer, gym and lighter output. Do not overload the day.',focus:['Sleep','devotion','recovery']}};
let state=S.get('state',null);if(!state){state={mode:'normal',page:'dashboard',zoom:34,calendarView:'week',calendarSearch:'',calendarFilters:Object.fromEntries(cats.map(c=>[c,true])),weekOffset:0,timer:{task:'Focus Session',seconds:25*60,running:false,last:null,sound:'Chime'},top3:[],layout:['today','timer','priorities','calendar','finance','bible'],priorities:[{id:1,name:'Morning devotion',cat:'ministry',duration:30,importance:10,urgency:9,progress:0,due:'daily'},{id:2,name:'Wednesday Bible Study prep',cat:'ministry',duration:180,importance:10,urgency:10,progress:0,due:'Tuesday'},{id:3,name:'Coursera cybersecurity',cat:'studies',duration:60,importance:9,urgency:7,progress:0,due:'weekly'},{id:4,name:'Uber income block',cat:'finance',duration:120,importance:8,urgency:7,progress:0,due:'weekend'},{id:5,name:'Gym / health',cat:'health',duration:75,importance:8,urgency:6,progress:0,due:'daily'},{id:6,name:'Family meeting prep',cat:'family',duration:45,importance:8,urgency:5,progress:0,due:'2nd Sunday'}],debts:[{id:1,name:'Credit Card',balance:2000,apr:24,min:75,extra:225,target:0},{id:2,name:'Car',balance:4200,apr:6,min:250,extra:100,target:0}],reports:[],bible:{version:'KJV',book:'John',chapter:15,highlights:{},notes:{}}};S.set('state',state)}
function save(){S.set('state',state)}
function now(){return new Date()}function pad(n){return String(n).padStart(2,'0')}function iso(d){return d.toISOString().slice(0,10)}function mins(t){let[a,b]=t.split(':').map(Number);return a*60+b}function time(m){return `${pad(Math.floor(m/60))}:${pad(m%60)}`}function niceDate(d){return d.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}
const nav=[['dashboard','Dashboard'],['calendar','Calendar'],['priorities','Priorities'],['routines','Routine'],['finance','Debt Projection'],['bible','Bible'],['reports','Reports'],['settings','Settings']];
function renderNav(){ $('#nav').innerHTML=nav.map(([id,n])=>`<button class="${state.page===id?'active':''}" onclick="go('${id}')">${n}</button>`).join('')}
function renderModes(){ $('#modebar').innerHTML=Object.entries(modes).map(([id,m])=>`<button class="chip ${state.mode===id?'active':''}" onclick="setMode('${id}')">${m.label}</button>`).join('');document.body.className='mode-'+state.mode}
function go(p){state.page=p;save();render()}function setMode(m){state.mode=m; if(m==='vacation'){state.calendarFilters.work=false;state.calendarFilters.rest=true}else if(m==='heavy-ministry'){state.calendarFilters.ministry=true;state.calendarFilters.studies=false}else if(m==='financial-push'){state.calendarFilters.finance=true;state.calendarFilters.rest=false}else if(m==='recovery'){state.calendarFilters.rest=true;state.calendarFilters.finance=false} save();render()}
function tickClock(){const d=now();$('#liveClock').textContent=d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit',second:'2-digit'});$('#liveDate').textContent=niceDate(d);timerTick()}setInterval(tickClock,1000);
function timerTick(){let t=state.timer;if(!t.running)return;let n=Date.now();let elapsed=Math.floor((n-(t.last||n))/1000);if(elapsed<=0)return;t.last=n;t.seconds=Math.max(0,t.seconds-elapsed);if(t.seconds===0){t.running=false;playSound();addReport('Timer Completed',t.task,'focus',0,'Timer finished.')}save();updateTimerDom()}
function updateTimerDom(){let el=$('#timerNumber');if(el)el.textContent=fmt(state.timer.seconds);let el2=$('#timerLabel');if(el2)el2.textContent=state.timer.task}
function fmt(s){return `${pad(Math.floor(s/60))}:${pad(s%60)}`}
function startTimer(name,min){state.timer={...state.timer,task:name||state.timer.task,seconds:(min||Math.ceil(state.timer.seconds/60))*60,running:true,last:Date.now()};save();render()}function pauseTimer(){state.timer.running=false;save();render()}function stopTimer(){state.timer.running=false;state.timer.seconds=25*60;save();render()}function setTimerMin(){let m=Number($('#timerMin')?.value||25);state.timer.seconds=m*60;state.timer.task=$('#timerTask')?.value||state.timer.task;save();render()}function playSound(){try{let ctx=new AudioContext();let osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=state.timer.sound==='Bell'?'sine':state.timer.sound==='Soft Pulse'?'triangle':'square';osc.frequency.value=state.timer.sound==='Bell'?880:state.timer.sound==='Soft Pulse'?523:660;gain.gain.setValueAtTime(.001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.25,ctx.currentTime+.03);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+1.1);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+1.2)}catch(e){}}
function addReport(name,item,cat,min,note){state.reports.unshift({id:Date.now(),date:new Date().toISOString(),name,item,cat,min,note});save()}
function weekStart(offset=0){let d=now();let diff=d.getDay();d.setHours(0,0,0,0);d.setDate(d.getDate()-diff+(offset*7));return d}
function nthWeekdayOfMonth(d){return Math.ceil(d.getDate()/7)}
function routineEventsForDay(d){let dow=d.getDay(),nth=nthWeekdayOfMonth(d),arr=[];let add=(title,start,end,cat,detail='')=>arr.push({title,start,end,cat,detail,date:iso(d)});
 add('Morning devotion','05:30','06:00','ministry','Daily priority');add('Prayer','12:00','12:10','ministry','Midday prayer');add('Prayer','15:00','15:10','ministry','3 PM prayer');add('Night devotion','21:45','22:15','ministry','Prayer and reading');
 if(dow>=1&&dow<=5){add('Work','09:00','18:00','work',dow===1||dow===5?'Work from home':'Office day')}
 if(dow===1||dow===5)add('Gym','07:30','09:00','health','WFH gym time'); if(dow>=2&&dow<=4){add('Gym','06:15','07:30','health','Office day gym');add('Travel to work','08:00','09:00','work','Commute') ;add('Travel home','18:00','19:00','work','Commute')}
 if(dow===0){add('Travel to church','07:25','08:00','ministry','35 min travel');add('Church','08:00','14:00','ministry','Sunday church');add('Bible Study prep','17:00','20:00','ministry','Minimum 3 hours'); if(nth===2){add('Family meeting prep','15:30','16:30','family','Prep notes for family meeting')}}
 if(dow===1)add('Bible Study prep','22:00','23:00','ministry','Study block'); if(dow===2)add('Bible Study prep','19:30','23:00','ministry','Deep prep block'); if(dow===3){add('Fasting','06:00','19:00','ministry','Wednesday fast');add('Bible Study','19:30','21:30','ministry','No Coursera before Bible Study')}
 if(dow===5){add('Uber Night','22:00','23:00','finance','Continues late into Saturday')}
 if(dow===6){if(nth===1)add('Leadership Meeting','11:00','14:00','ministry','1st Saturday'); if(nth>=3)add('Worship Team Practice','09:00','11:00','ministry','3rd/4th/5th Saturday');}
 return arr}
function eventsForWeek(){let ws=weekStart(state.weekOffset),ev=[];for(let i=0;i<7;i++){let d=new Date(ws);d.setDate(ws.getDate()+i);ev.push(...routineEventsForDay(d))}return ev}
function busySlotsFor(date){return routineEventsForDay(date).map(e=>[mins(e.start),mins(e.end),e])}
function freeSlots(date,minDuration=30){let start=6*60,end=23*60,busy=busySlotsFor(date).sort((a,b)=>a[0]-b[0]);let cur=start,out=[];for(let [s,e] of busy){if(s-cur>=minDuration)out.push([cur,s]);cur=Math.max(cur,e)}if(end-cur>=minDuration)out.push([cur,end]);return out}
function candidatesToday(){let d=now(),slots=freeSlots(d,30);let dow=d.getDay();return state.priorities.filter(p=>!p.doneToday).map(p=>{let min=p.cat==='finance'?120:p.cat==='studies'?60:p.duration||30;let valid=slots.find(([s,e])=>e-s>=min);let blocked=(p.cat==='studies'&&dow===3);return {...p,min,valid,score:(p.importance*2+p.urgency+(p.progress<100?5:0))-(blocked?99:0),blocked}}).filter(p=>p.valid&&!p.blocked).sort((a,b)=>b.score-a.score)}
function dashboard(){let mode=modes[state.mode],cand=candidatesToday(),top=state.top3.map(id=>state.priorities.find(p=>p.id===id)).filter(Boolean);if(!top.length)top=cand.slice(0,3);let cards={
 today:`<div class="card span7 widget hero"><div class="kicker">Today</div><h2>What do I do today?</h2><p class="muted">${mode.hint}</p><div class="stack">${top.map(p=>priorityLine(p,true)).join('')||'<p class="muted">Choose your Top 3 for today.</p>'}</div><div class="row" style="margin-top:12px"><button class="primary" onclick="openTop3()">Choose Today\'s Top 3</button><button class="ghost" onclick="go('calendar')">See schedule</button></div></div>`,
 timer:`<div class="card span5 widget"><h2>Focus Timer</h2><div class="timerDock"><div><div id="timerLabel" class="muted">${state.timer.task}</div><div id="timerNumber" class="timerNum">${fmt(state.timer.seconds)}</div><div class="soundBadge tiny">Sound: ${state.timer.sound} <button class="ghost" onclick="playSound()">Test</button></div></div><div class="timerControls"><input id="timerTask" placeholder="Task" value="${state.timer.task}"><input id="timerMin" type="number" value="${Math.ceil(state.timer.seconds/60)}" min="1"><button class="primary timerBtn" onclick="setTimerMin();startTimer()">Start</button><button class="ghost timerBtn" onclick="pauseTimer()">Pause</button><button class="danger timerBtn" onclick="stopTimer()">Stop</button></div></div></div>`,
 priorities:`<div class="card span6 widget"><h2>Priority Progress</h2><div class="stack">${state.priorities.slice(0,5).map(p=>priorityLine(p,false)).join('')}</div><button class="ghost" onclick="go('priorities')">Manage priorities</button></div>`,
 calendar:`<div class="card span6 widget"><h2>Next Open Slots</h2>${freeSlots(now(),30).slice(0,4).map(([s,e])=>`<div class="item"><span class="badge">${time(s)}-${time(e)}</span> <span class="muted">${e-s} min open</span></div>`).join('')||'<p class="muted">No open slots left today.</p>'}<button class="ghost" onclick="go('calendar')">Open calendar</button></div>`,
 finance:`<div class="card span6 widget"><h2>Debt Projection</h2>${debtSummary()}<button class="ghost" onclick="go('finance')">Open projection</button></div>`,
 bible:`<div class="card span6 widget"><h2>Bible Reader</h2><p class="muted">YouVersion-inspired reader with versions, highlights, notes, and lookup.</p><div class="verse"><span class="verseNum">John 15:5</span>I am the vine, ye are the branches...</div><button class="ghost" onclick="go('bible')">Open Bible</button></div>`};
 return `<div class="grid"><div class="card span12 modeHero"><div class="row"><div><div class="kicker">Mode Behavior</div><h2>${mode.label}</h2><p class="muted">${mode.hint}</p><div>${mode.focus.map(x=>`<span class="pill">${x}</span>`).join('')}</div></div><button class="ghost" onclick="go('routines')">Modify routine</button></div></div></div><div class="dashboard-grid" id="dashGrid">${state.layout.map(id=>cards[id]).join('')}</div>`}
function priorityLine(p,withFit){let done=p.doneToday;let fit='';if(withFit){let c=candidatesToday().find(x=>x.id===p.id);fit=c?`<span class="pill">Best: ${time(c.valid[0])}-${time(c.valid[0]+c.min)}</span>`:''}return `<div class="item ${done?'done':''}" onclick="editPriority(${p.id})"><div class="row"><div><div class="name">${p.name}</div><span class="pill ${p.cat}">${p.cat}</span><span class="pill">${p.duration} min</span>${fit}</div><div><button class="ghost" onclick="event.stopPropagation();startTimer('${p.name}',${p.duration})">Start</button><button class="primary" onclick="event.stopPropagation();markDone(${p.id})">Done</button></div></div><div class="progress"><div class="bar" style="width:${p.progress||0}%"></div></div></div>`}
function markDone(id){let p=state.priorities.find(x=>x.id===id);if(p){p.doneToday=true;p.progress=Math.min(100,(p.progress||0)+25);addReport('Completed',p.name,p.cat,p.duration,'Marked done from dashboard.');save();render()}}
function openTop3(){let cand=candidatesToday();openModal('Choose Today\'s Top 3',`<p class="muted">Only items that fit today are shown. Uber requires 2 hours. Coursera requires 1 hour and is blocked before Wednesday Bible Study.</p><div class="stack">${cand.map(p=>`<div class="item ${state.top3.includes(p.id)?'selectedTop':''}" onclick="toggleTop3(${p.id})"><div class="row"><div><div class="name">${p.name}</div><span class="pill">${p.cat}</span><span class="pill">${p.min} min</span><span class="pill">fits ${time(p.valid[0])}-${time(p.valid[0]+p.min)}</span></div><button class="ghost">Pick</button></div></div>`).join('')}</div><hr><input id="newTopName" placeholder="Add new priority"><select id="newTopCat">${cats.map(c=>`<option>${c}</option>`)}</select><input id="newTopMin" type="number" value="30"><button class="primary" onclick="addTopPriority()">Add priority</button>`) }
function toggleTop3(id){if(state.top3.includes(id))state.top3=state.top3.filter(x=>x!==id);else if(state.top3.length<3)state.top3.push(id);save();openTop3()}
function addTopPriority(){let n=$('#newTopName').value.trim();if(!n)return;let p={id:Date.now(),name:n,cat:$('#newTopCat').value,duration:Number($('#newTopMin').value||30),importance:7,urgency:7,progress:0,due:'today'};state.priorities.push(p);state.top3.push(p.id);state.top3=state.top3.slice(-3);save();openTop3()}
function editPriority(id){let p=state.priorities.find(x=>x.id===id);openModal('Edit Priority',`<label>Name</label><input id="epn" value="${p.name}"><label>Category</label><select id="epc">${cats.map(c=>`<option ${p.cat===c?'selected':''}>${c}</option>`)}</select><label>Minutes</label><input id="epd" type="number" value="${p.duration}"><label>Progress %</label><input id="epp" type="number" value="${p.progress||0}"><div class="row"><button class="primary" onclick="savePriority(${id})">Save</button><button class="primary" onclick="markDone(${id});closeModal()">Mark Done</button><button class="ghost" onclick="startTimer('${p.name}',${p.duration});closeModal()">Start Timer</button></div>`)}
function savePriority(id){let p=state.priorities.find(x=>x.id===id);p.name=$('#epn').value;p.cat=$('#epc').value;p.duration=Number($('#epd').value);p.progress=Number($('#epp').value);save();closeModal();render()}
function calendar(){return `<div class="card span12"><div class="calendar-tools"><button class="primary" onclick="state.weekOffset=0;save();render()">Today</button><button class="ghost" onclick="state.weekOffset--;save();render()">Prev</button><button class="ghost" onclick="state.weekOffset++;save();render()">Next</button><button class="ghost" onclick="state.zoom=Math.max(24,state.zoom-8);document.documentElement.style.setProperty('--slot',state.zoom+'px');save();render()">Zoom -</button><button class="ghost" onclick="state.zoom=Math.min(76,state.zoom+8);document.documentElement.style.setProperty('--slot',state.zoom+'px');save();render()">Zoom +</button><input id="calSearch" placeholder="Search calendar" value="${state.calendarSearch}" oninput="state.calendarSearch=this.value;save();renderCalendarOnly()">${cats.map(c=>`<label class="pill"><input type="checkbox" ${state.calendarFilters[c]?'checked':''} onchange="state.calendarFilters['${c}']=this.checked;save();renderCalendarOnly()"> ${c}</label>`).join('')}</div><div id="calendarOnly">${weekCalendar()}</div></div>`}
function renderCalendarOnly(){let el=$('#calendarOnly');if(el)el.innerHTML=weekCalendar();let input=$('#calSearch'); if(input){input.focus();input.selectionStart=input.selectionEnd=input.value.length}}
function weekCalendar(){document.documentElement.style.setProperty('--slot',state.zoom+'px');let ws=weekStart(state.weekOffset),ev=eventsForWeek().filter(e=>state.calendarFilters[e.cat]&&(e.title+e.detail).toLowerCase().includes(state.calendarSearch.toLowerCase()));let today=iso(now());let html='<div class="weekWrap"><div class="weekGrid"><div class="calCell calHead">Time</div>';for(let i=0;i<7;i++){let d=new Date(ws);d.setDate(ws.getDate()+i);html+=`<div class="calCell calHead ${iso(d)===today?'todayCol':''}">${dayNames[d.getDay()]}<br>${d.toLocaleDateString([], {month:'short',day:'numeric',year:'numeric'})}</div>`}for(let m=6*60;m<=23*60;m+=30){html+=`<div class="calCell timeCell">${time(m)}</div>`;for(let i=0;i<7;i++){let d=new Date(ws);d.setDate(ws.getDate()+i);let dayEv=ev.filter(e=>e.date===iso(d)&&mins(e.start)<=m&&mins(e.end)>m);let isNow=iso(d)===today&&Math.abs((now().getHours()*60+now().getMinutes())-m)<30;html+=`<div class="calCell ${iso(d)===today?'todayCol':''}">${isNow?'<div class="nowLine"></div>':''}${dayEv.map(e=>`<div class="block ${e.cat}" title="${e.title} ${e.start}-${e.end}">${e.title}</div>`).join('')}</div>`}}html+='</div></div>';return html}
function prioritiesPage(){return `<div class="grid"><div class="card span8"><h2>Priorities</h2><div class="stack">${state.priorities.map(p=>priorityLine(p,false)).join('')}</div></div><div class="card span4"><h2>Add Priority</h2><input id="pn" placeholder="Name"><select id="pc">${cats.map(c=>`<option>${c}</option>`)}</select><input id="pd" type="number" value="30"><button class="primary" onclick="addPriority()">Add</button></div></div>`}function addPriority(){state.priorities.push({id:Date.now(),name:$('#pn').value,cat:$('#pc').value,duration:Number($('#pd').value),importance:7,urgency:7,progress:0,due:'custom'});save();render()}
function routines(){let mode=modes[state.mode];return `<div class="grid"><div class="card span12 modeHero"><h2>Routine adapts to ${mode.label}</h2><p class="muted">${mode.hint}</p>${mode.focus.map(x=>`<span class="pill">${x}</span>`).join('')}</div><div class="card span12"><h2>Weekly Routine</h2><p class="muted">Fixed blocks currently include work, commutes, gym, prayers, church, Bible prep, Wednesday fast/Bible Study, Friday Uber night, leadership, worship practice, and family meeting prep.</p><button class="ghost" onclick="go('calendar')">View on calendar</button></div></div>`}
function finance(){return `<div class="grid"><div class="card span5"><h2>Debt Accounts</h2><div class="stack">${state.debts.map(d=>`<div class="item" onclick="editDebt(${d.id})"><div class="row"><div><div class="name">${d.name}</div><span class="pill">Balance $${d.balance}</span><span class="pill">APR ${d.apr}%</span></div><span class="badge">${payoff(d).months} mo</span></div></div>`).join('')}</div></div><div class="card span7"><h2>Projection Engine</h2>${debtSummary(true)}<h2>What-if</h2><div class="grid"><input id="whatBal" type="number" value="${state.debts[0]?.balance||0}" placeholder="Balance"><input id="whatPay" type="number" value="300" placeholder="Monthly payment"><input id="whatApr" type="number" value="24" placeholder="APR"><button class="primary" onclick="calcWhatIf()">Calculate</button></div><div id="whatResult"></div></div></div>`}
function payoff(d){let bal=Number(d.balance),rate=Number(d.apr)/100/12,pay=Number(d.min)+Number(d.extra);let months=0,interest=0;if(pay<=0)return{months:999,interest:0};while(bal>0&&months<600){let int=bal*rate;interest+=int;bal=bal+int-pay;months++}return{months,interest:Math.round(interest)}}function debtSummary(full=false){let total=state.debts.reduce((a,d)=>a+Number(d.balance),0);let lines=state.debts.map(d=>{let p=payoff(d);let date=new Date();date.setMonth(date.getMonth()+p.months);return `<div class="item"><div class="row"><div><div class="name">${d.name}</div><span class="pill">$${d.balance}</span><span class="pill">$${Number(d.min)+Number(d.extra)}/mo</span></div><div class="metric" style="font-size:22px">${p.months} mo</div></div><p class="muted tiny">Projected payoff: ${date.toLocaleDateString([], {month:'long',year:'numeric'})}. Interest about $${p.interest}.</p></div>`}).join('');return `<div class="metric">$${total.toLocaleString()}</div><p class="muted">Total debt tracked</p>${full?lines:''}`}function editDebt(id){let d=state.debts.find(x=>x.id===id);openModal('Edit Debt',`<input id="dn" value="${d.name}"><label>Balance</label><input id="db" type="number" value="${d.balance}"><label>APR</label><input id="da" type="number" value="${d.apr}"><label>Minimum payment</label><input id="dm" type="number" value="${d.min}"><label>Extra payment</label><input id="de" type="number" value="${d.extra}"><button class="primary" onclick="saveDebt(${id})">Save</button>`)}function saveDebt(id){let d=state.debts.find(x=>x.id===id);d.name=$('#dn').value;d.balance=Number($('#db').value);d.apr=Number($('#da').value);d.min=Number($('#dm').value);d.extra=Number($('#de').value);save();closeModal();render()}function calcWhatIf(){let bal=Number($('#whatBal').value),pay=Number($('#whatPay').value),apr=Number($('#whatApr').value),d={balance:bal,apr,min:pay,extra:0};let p=payoff(d);let date=new Date();date.setMonth(date.getMonth()+p.months);$('#whatResult').innerHTML=`<div class="item"><div class="name">At $${pay}/month</div><p>Paid off in <b>${p.months} months</b>, around <b>${date.toLocaleDateString([], {month:'long',year:'numeric'})}</b>. Estimated interest: <b>$${p.interest}</b>.</p></div>`}
const bibleData={KJV:{John:{15:[,'I am the true vine, and my Father is the husbandman.','Every branch in me that beareth not fruit he taketh away...','Now ye are clean through the word which I have spoken unto you.','Abide in me, and I in you...','I am the vine, ye are the branches: He that abideth in me, and I in him...','If a man abide not in me, he is cast forth as a branch...','If ye abide in me, and my words abide in you, ye shall ask what ye will...','Herein is my Father glorified, that ye bear much fruit...','As the Father hath loved me, so have I loved you...','If ye keep my commandments, ye shall abide in my love...','These things have I spoken unto you, that my joy might remain in you...'],Psalms:{23:[,'The LORD is my shepherd; I shall not want.','He maketh me to lie down in green pastures: he leadeth me beside the still waters.','He restoreth my soul: he leadeth me in the paths of righteousness for his name’s sake.','Yea, though I walk through the valley of the shadow of death, I will fear no evil...']},Proverbs:{3:[,'My son, forget not my law; but let thine heart keep my commandments:','For length of days, and long life, and peace, shall they add to thee.','Let not mercy and truth forsake thee...','So shalt thou find favour and good understanding in the sight of God and man.','Trust in the LORD with all thine heart; and lean not unto thine own understanding.','In all thy ways acknowledge him, and he shall direct thy paths.']}}};
function bible(){let b=state.bible,verses=(bibleData.KJV[b.book]?.[b.chapter])||[];return `<div class="bibleShell"><div class="biblePane"><div class="kicker">Bible Reader</div><h2>Scripture</h2><select id="bv" onchange="state.bible.version=this.value;save();render()"><option>KJV</option><option>ASV online lookup</option><option>WEB online lookup</option></select><select id="bb" onchange="state.bible.book=this.value;save();render()">${['John','Psalms','Proverbs'].map(x=>`<option ${b.book===x?'selected':''}>${x}</option>`)}</select><input id="bc" type="number" value="${b.chapter}" onchange="state.bible.chapter=Number(this.value);save();render()"><button class="primary" onclick="fetchBible()">Online Lookup</button><p class="muted tiny">Modern translations like NIV/ESV/NLT require licensed APIs. This app can use public-domain/API sources.</p><h3>Highlights</h3><div>${Object.keys(b.highlights).map(k=>`<span class="pill">${k}</span>`).join('')||'<p class="muted">No highlights yet.</p>'}</div></div><div class="biblePane"><h2>${b.book} ${b.chapter} <span class="pill">${b.version}</span></h2><div id="onlineBible"></div>${verses.slice(1).map((v,i)=>{let key=`${b.book}.${b.chapter}.${i+1}`;return `<div class="verse ${b.highlights[key]?'highlight':''}" onclick="toggleHighlight('${key}')"><span class="verseNum">${i+1}</span>${v}${b.notes[key]?`<div class="noteBox">${b.notes[key]}</div>`:''}<div><button class="ghost" onclick="event.stopPropagation();noteVerse('${key}')">Note</button></div></div>`}).join('')}</div></div>`}
function toggleHighlight(k){state.bible.highlights[k]=!state.bible.highlights[k];if(!state.bible.highlights[k])delete state.bible.highlights[k];save();render()}function noteVerse(k){let n=prompt('Note for '+k,state.bible.notes[k]||'');if(n!==null){state.bible.notes[k]=n;save();render()}}async function fetchBible(){let ref=`${state.bible.book} ${state.bible.chapter}`;let box=$('#onlineBible');box.innerHTML='<p class="muted">Loading public Bible API...</p>';try{let r=await fetch('https://bible-api.com/'+encodeURIComponent(ref));let j=await r.json();box.innerHTML=`<div class="item"><div class="name">${j.reference||ref}</div><p style="white-space:pre-wrap;line-height:1.7">${j.text||'No text returned.'}</p></div>`}catch(e){box.innerHTML='<p class="muted">Online Bible lookup failed. Check internet/API availability.</p>'}}
function reports(){let f=S.get('reportFilter','');let reps=state.reports.filter(r=>(r.name+r.item+r.cat).toLowerCase().includes(f.toLowerCase()));return `<div class="grid"><div class="card span12"><h2>Reports</h2><input placeholder="Filter reports by name/category/item" value="${f}" oninput="S.set('reportFilter',this.value);render()"><div class="stack" style="margin-top:12px">${reps.map(r=>`<div class="item reportCard" onclick="openReport(${r.id})"><div class="row"><div><div class="name">${r.name}: ${r.item}</div><span class="pill">${r.cat}</span><span class="pill">${new Date(r.date).toLocaleString()}</span></div><span class="badge">${r.min||0} min</span></div></div>`).join('')||'<p class="muted">No reports yet. Mark priorities done or finish timers.</p>'}</div></div></div>`}function openReport(id){let r=state.reports.find(x=>x.id===id);openModal(r.name,`<p><b>Item:</b> ${r.item}</p><p><b>Category:</b> ${r.cat}</p><p><b>Date:</b> ${new Date(r.date).toLocaleString()}</p><p><b>Minutes:</b> ${r.min||0}</p><p>${r.note||''}</p>`)}
function settings(){return `<div class="grid"><div class="card span6"><h2>Timer Settings</h2><label>Sound</label><select onchange="state.timer.sound=this.value;save();render()"><option ${state.timer.sound==='Chime'?'selected':''}>Chime</option><option ${state.timer.sound==='Bell'?'selected':''}>Bell</option><option ${state.timer.sound==='Soft Pulse'?'selected':''}>Soft Pulse</option></select><button class="ghost" onclick="playSound()">Test sound</button></div><div class="card span6"><h2>App Tools</h2><button class="ghost" onclick="exportData()">Export Backup</button><button class="danger" onclick="if(confirm('Reset done flags for today?')){state.priorities.forEach(p=>p.doneToday=false);save();render()}">Reset Today Done</button></div></div>`}function exportData(){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kingdomos-backup.json';a.click()}
function openModal(t,b){$('#modalTitle').textContent=t;$('#modalBody').innerHTML=b;$('#modal').classList.add('open')}function closeModal(){$('#modal').classList.remove('open')}
function render(){renderNav();renderModes();let titles={dashboard:['Dashboard','Simple command center. No repeats.'],calendar:['Calendar','30-minute week view with search, filters and zoom.'],priorities:['Priorities','Click anything to edit, start timer, or mark done.'],routines:['Routine','Your recurring weekly rhythm and mode behavior.'],finance:['Debt Projection','Editable, advanced payoff projections.'],bible:['Bible','Reader, lookup, highlights and notes.'],reports:['Reports','Named completion and timer reports.'],settings:['Settings','Customize KingdomOS.']};$('#pageTitle').textContent=titles[state.page][0];$('#pageSub').textContent=titles[state.page][1];let map={dashboard,calendar,priorities:prioritiesPage,routines,finance,bible,reports,settings};$('#content').innerHTML=map[state.page]();enableDrag();tickClock()}
function enableDrag(){let grid=$('#dashGrid');if(!grid)return;let drag=null;grid.querySelectorAll('.widget').forEach((w,i)=>{w.draggable=true;w.ondragstart=()=>{drag=i;w.classList.add('dragging')};w.ondragend=()=>w.classList.remove('dragging');w.ondragover=e=>e.preventDefault();w.ondrop=()=>{let arr=[...state.layout];let [m]=arr.splice(drag,1);arr.splice(i,0,m);state.layout=arr;save();render()}})}
render();
